secrets:
    acme_email: ENC[AES256_GCM,data:o+2HnrEqa/uXJwqUwdYU14FiZYPfLcKqkQ==,iv:1ouUU4ewzRL4ZDnwJm6BTVg3a64iC5+I2v+AWIF8W2Q=,tag:7ytv959cVmgSmXMC7A8zxA==,type:str]
    webapp:
        env:
            MAPBOX_TOKEN: ENC[AES256_GCM,data:7Ka4BvQh6NDw9NKUcgGjLwxNHOqhVrZEj/DcGnyv1nXQIG/2WWGGHazAFWUCFpCUmCSaTPSkyLHPFyGQtQ7VAON3AG3tHtv5JvcBb4KDYrjAIzxhAAiHMYFtVJs=,iv:X0YL2dW42TUidJdBlRKb4Vq86X1OzHqipNHTBxmE7ds=,tag:KDH9NwDy6ghqdkXeZxuHgg==,type:str]
    backend:
        env:
            JWT_SECRET: ENC[AES256_GCM,data:8qGviTFMOv9QyoNVwnlFNZ2PmvedbKJM,iv:rmZgs8h2QVsokzMzdGdEcInBLv8AX3xFUjkGhTf3sF0=,tag:SUJpMaIGAb14yg8RxCVUtA==,type:str]
            MAPBOX_TOKEN: ENC[AES256_GCM,data:qK6iTYKiWfkvXBodm8zVmfr5ACTTz1+7Pt7Q/hwgv3SYERyo5NyqfsvbVKuDAD90kTCNODpSwUApJE6do/Umedg4s8mrnHXCckIDbX5BztoeHJBehsUC54ELcrQ=,iv:b65yqfdoOX366UXt7HS6nhL8hlZn4l5hQfrhI6NXc+I=,tag:vF48V+TRS5g9ezXhzAJnPw==,type:str]
            PRIVATE_KEY_PASSPHRASE: ENC[AES256_GCM,data:05WXBFKIk0BtfUYmkWSwAP+/Y7v18LUow4X/,iv:y7VyymcoRLr2CK96BiErXvKP2Gn/QhECBZyeP+wo8LA=,tag:Hg/fIGyIDMY8P3mWfVupCw==,type:str]
            #ENC[AES256_GCM,data:llx+JN8fRqwrLd2ahkmPrhPwcGIkn695l3Ox8VEs9YAR+1wpz3yujA==,iv:4Ctez8zMeqo3cpCCUVy6ZP4T1Z/myPw/FTq+++YAYbc=,tag:al/J8DLqNz6CoLl+TgUdOw==,type:comment]
            EMAIL_DEFAULT_SENDER: ENC[AES256_GCM,data:z1EyEokf/TNkFLhRzsCbHew/6T8=,iv:Satr1c8aZQE73ZolC6n+PO74r+Gj3un5Mj0DIYb3n14=,tag:iK6l0GXuhLauBtFXTmLyKQ==,type:str]
            SMTP_HOST: ENC[AES256_GCM,data:r0qbaUBB3CSUHR76,iv:TJIx71HW1aBB0sCEd1TB/tTgPBxLR1sdGAEf0t7Qilg=,tag:arXYtwVbIXVaUJpyommokQ==,type:str]
            SMTP_USERNAME: ENC[AES256_GCM,data:lZ05DvSu,iv:Tyu7poao1shqKGd/sjTCgGNHU1xgRpjwjMRd+ArGf6o=,tag:dKms4G683JvFzja7YOwYKg==,type:str]
            SMTP_PASSWORD: ENC[AES256_GCM,data:c9rnPIaKHIh2LNIJON3ib1IsA09OWGchDxRPRpvrtJw=,iv:08Acxl74lJbYtEEU6crVIYRXwkER8t1XPrhBA2PwEio=,tag:F0xrrt2PkBUMEyp7a81ssw==,type:str]
            SMTP_PORT: ENC[AES256_GCM,data:MGmv,iv:IFg6oEncN0ICEmw96XL4EuPKqEZ6KLwU5FJYkveMSpY=,tag:kIVXlt0o5TfhOtRVqU/c4w==,type:str]
            SMTP_IGNORE_TLS: ENC[AES256_GCM,data:ORAIWtg=,iv:6X4V3RDeYHrFdBTjsb3Ji0KWsZ2meL8ilqHNGQbcV/M=,tag:R87FgoQwqpes+0ejcOlrPg==,type:str]
            #ENC[AES256_GCM,data:wEE3/SPsZqy9LATseOZG7LsCbjG5gY4VUT/TzxhHLJqcYP5I,iv:gcOA0XiUGWq15G4zTRPZ0qZ/XYMTjr+9krbOx0dwpeY=,tag:jd8LTiVT7UQShqMR9zZUZA==,type:comment]
            SMTP_SECURE: ENC[AES256_GCM,data:PowbGhU=,iv:a1dK5AVySu749vPQvX9OLfMuD+tZkLNtXTMr17+4KuA=,tag:fuJQ7c4RBl25If01MSAmug==,type:str]
            SMTP_DKIM_PRIVATKEY: null
            SMTP_DKIM_DOMAINNAME: null
            SMTP_DKIM_KEYSELECTOR: null
            NEO4J_USERNAME: null
            NEO4J_PASSWORD: null
            REDIS_PASSWORD: null
            IMAGOR_SECRET: ENC[AES256_GCM,data:nPGDGgjnszFpvNk/ucl63/4o1Yd+rA7ty9PtHcIuOQ0=,iv:kN7ys7qyizLYINHUUTAb6UJh2TF6nnWcUmKKgB5sIdA=,tag:eZNlpZO4K2cNUnlvS1orag==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dA6Ok1g5jqlyP6jKaRP7WpH4poQ=,iv:yGIWmSoDd+1fm+NKuzipm+Z1C2XVJdOTY9vWIKLy75c=,tag:H18HVmRjP3iyJiixCtpNoQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BTvIEYBQhtOvQbzUBotrslFHhHY9AQobMj7tq3lapS4/gJZBUJ/i3g==,iv:H4MZoTVRngfFwSBgqp4qCawGbDxNNKtQC6PJXWEQdcI=,tag:0sP0Ym/fPs4wJdZvRAG3Jg==,type:str]
            AWS_ENDPOINT: ENC[AES256_GCM,data:LefUZKGs2pK/RyD83qCLy0c1mkC6E7CUvmWgMztoWaNgBAc=,iv:5nmUUVqx3iFJ/2/f2KOgVVhJlqcVS1IT1lCeRPX9Xr8=,tag:LzA866gXskHUEp0+oGnn4g==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:V/qfzTm0lP8PTA==,iv:7oPrKB+6ceAf+C51Nh1H3To+/LYG6+tm9vJi7x+HNmc=,tag:vdZJG8V6/TLpDxHboXWS2w==,type:str]
            AWS_BUCKET: ENC[AES256_GCM,data:Togaqd7ixlF7GVT1jHn43pMLoJvU,iv:eHpwSSschVe2GVQDTFIWTwCi2uOE4z9XOF1VTRk8FLY=,tag:XOx1jPG37NuP2KU0QSjTLw==,type:str]
    neo4j:
        env:
            NEO4J_USERNAME: ""
            NEO4J_PASSWORD: ""
    imagor:
        env:
            HTTP_LOADER_BASE_URL: ENC[AES256_GCM,data:By8W4EhROKwKBi1Zv/R3Rbq91kvl22OOZWhRdz3n0fRzZUE=,iv:L17wYXJimfSB8jKlQvAa9hkZM6BHsrLwVoUm4F+ddsc=,tag:7ufs8lVNfNozjdbXOd372A==,type:str]
            IMAGOR_SECRET: ENC[AES256_GCM,data:EoUtgQJ9GHuhrt209iQMSs2SayaUJi1zIZC+TuEr4KQ=,iv:SU7KtV0izan3OUXN0A1vpmEPXdTogfBeEPzfcqdGIKQ=,tag:/IzzvWuFE/gHiZalXWshfw==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:B25aseDb9E3LXiSuZD+jUrfZ0Sc=,iv:h3TMMh2ULYC4cGSF8WpX8y6w/x/A/bFlk47rIFoFEek=,tag:0FRXAEXucH9JvxPUEsPUMg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KRBRWyYzisHeGWiUJo3bf39ZGFTa+bJTfBTyDxHBtyrj1jmU5P/9qQ==,iv:PfwjEPH247KtZlUGHcEG/Hp2ismgBpCDYXWRM7IMTbQ=,tag:1jhI1bUIOqU9f5YHVnuocA==,type:str]
            AWS_ENDPOINT: ENC[AES256_GCM,data:CVLJNnBjb45rMM/ixlUv+vPftUkKbQYuhhui0JRSgqeZp0A=,iv:IsWO4eVN6mBBs4mO1wryDwt9vdyGzQAAsDJVvL1oLNs=,tag:cP0CZQBtMS2OsE+/KN4AlA==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:cWKZd9XGdRcgjQ==,iv:cB2hTBDQ9d3uf/Mgthd/tsa529S+2KlkXCTZ6HXAVZ0=,tag:OF/87D0TDu/yEh6Bf163PA==,type:str]
            AWS_BUCKET: ENC[AES256_GCM,data:mlljAczY/xwp/+C2pkgALCDUZkiC,iv:PPQol5Yq6vWHYYRy1gg+UfuSHFHxXQlNpjqbBOOoQ2M=,tag:0RVAIoAmdmIgp2/udLjfiw==,type:str]
sops:
    age:
        - recipient: age1al36hkk8can83zpxq8qyy07gpv83hdw9vchfly5f264kanz405as283a00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MjZ5RGI0YTFIbDk3MnBs
            ODN3RUg3ZVhsS1dEeDdodFJaQzg2RjFpcm1vClNzV1NwdEFwaXJnclRNVTJIbzVk
            VEc3YUV4eWJLb04valdNV216SnhtbzQKLS0tIHpuR2JGZWp0WnNUdStuL1ZLU0FK
            eGEreGNJTnU1OTgxL2ljVVRjUUxraEkKvkV7G56/GtJLbLVHvrq+rJ8npBckvww/
            Tq7/k/YmGV764d3Zb0Vs6TNJhoOvKF6sK645wrFlSzVNj51UxkhWYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1llp6k66265q3rzqemxpnq0x3562u20989vcjf65fl9s3hjhgcscq6mhnjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWTI4M202SmlhbzJnckF3
            ODZrY3ZQQkRLZmQrNmg4Uys2d0JBWWJMWkN3CmNwUi9HT2VYd0paMnJScnFxSXB0
            YThaU2RqWFdHMXczQ1VmdFdJQmJSU00KLS0tIDk4TW5DdUNJY3dnS1JGQUluaTJw
            d3ErbWdrZ2I3ZU1ZZGZBZ1JZU0lZMUEKnQHREjKUZ6a2+Es7SlLY46h4NPdeaE8c
            w4My+za7IjGSyL6HKqxSBLUS4Q79cI3iBNu8SwikocmEkqQ/DWlC6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zycwtk6dkxj6vuqhj9jw7932ythky9p3att6df4z9qasyw8v5dxquejcmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTmhYKzUyUGJnRHhjTU5m
            TVVFOGl5d3ZFYzE4U216a1YvVUlXTGFvYTM4CkZaMTcvRk1CVDJwek9TT0UvOWMr
            SWNrb0pvYTZaTHM4aGRpcG9odDhyUm8KLS0tIEkrSmc4V2c0Q0ltWkdRZWQ5NFEr
            Y1VWV0JTRjVmWUU4U1pTZkVhbTVLREEKvCxhsCX//e7XawyJG3XeCGLOUqxCx9No
            To4JGg10ciWcW0eqyP5lQfwdlECkmPapNz8gaf40DVpPDij5Nja+zA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15arcg8x6ltnsacwalvny0h2d4d4wkdmax328mw3v5vda9zm97uqshtavmr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaHh6b3hpbFJrcHl6eHl6
            MkZmNUJWSTJRUFVNOHJaYld3QWUwSy93aEFNCjZTZnNZRlJRR3VEeXROOFBmY2Qz
            SHF2bWMvdm5zNi92SUFlc2FZcFl1Y1kKLS0tIG4wYzdKTWFKaExiTVlFa0tRdzVs
            bGFuMlF6bkw2Z1lGNmZTV1R0ZEs2T0EK78at74wFk1B5OgeMSKrGLl3sNiwrzitL
            0kcMVyxfV68mpjb0Cw2WtEUo0jFmKFXi7H5FbJeoPrDG0QFvIvgfsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1khw2eps099audp3uu5s9rk07qznllh5c8a43gv5dtpnq2a7lue6qrehn5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYXE0V2pFYnU5Slk5Nk5j
            Snh2UElZajhMZnlZTjVkcFBSMnF2VFJ6TG40ClBFQzV4SUpUZTZaSWpRdXNIdDBq
            ZHFUSG5uUHU0bXhhcEpCejh2elM1M2MKLS0tIEovMDdrUEs5blNvL3R0VGVaMVhw
            Q3V1UmU0OUtWRmRuQ1dtMFROUDF6NG8KRJRymV0GaOW7sENEqYogNK2HeArsuY8Y
            lVWepYYDoeRWwu7kmzORaEnW6G4m0F3rADfwMrQVTNvZ+1Xn/yFOXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6mzqe0cejajzt0c7nwdjz4xvs4hjct9d8hrgj60e7unzyfd7prsn0npe5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbHhMUElKUWhFMERGVWpz
            cFRwTVovOStYNUQ4czIxR25MUzNON2ZzRmc0CjNvOGd4bmdjWHhwdEMzTzJkQU1Y
            SHJrZG1pQ3pmZnZxWXh4bjkwN3ZvVFEKLS0tIHRhVDgzUHNsMHYrV0RoWCtmR0Nl
            Tkx0VFJpN1pZam4yeTNYU1Jnb1JyR1EKJSQYyAi9ZZr+njaXV/62nshPVLtWIcLY
            pwP8ikur4tKrbyg7H+/f3+9jPsr2Jw3xxgkeS4GL+DsTwrGDEwoaiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-30T12:51:00Z"
    mac: ENC[AES256_GCM,data:zgyr3gyuAw85enQo1lbGVCIBnl46m6TeKvnOgPAyMWbgEZ/EHoeAB8+dYSiFILHpDwjje9xTZZ4hUHA5i1Pvk9mIWh4foXuBKSx5S0UEGMfdaAQWN1mq5rUuemb/D/gjCSHLMTP7wZPTc5bSEb9/AA12VN1voMO6suEWTVpNOjw=,iv:mV/NJm4d23NUexZ3lTJhxqVIE7pp/Sp1gxfqNNwjf3I=,tag:utZDVvu8mwUn9QdcJ0TMgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
